#                                                 ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥
#                                                   ğŸ’»Pearl Rider ConfigğŸ’»
#                                                   ğŸ”¥Coded By Mike3132ğŸ”¥
#                                                   ğŸ’»Pearl Rider ConfigğŸ’»
#                                                 ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥

Version: 'Version 1.0'
ConfigVersion: '1.0'
##### WARNING: DO NOT CHANGE ANYTHING ABOVE THIS LINE IT WILL BREAK THE PLUGIN!#####

#âœâœâœâœâœPermissionsâœâœâœâœâœ
#pearlRider.Admin > Grants access to /PearlRider commands.
#pearlRider.Give > Grants access to giving custom ender pearls.
#pearlRider.use > Grants access to ride Ender Pearls.
#âœâœâœâœâœPermissionsâœâœâœâœâœ


#####You can Modify the following how you wish#####
#â™¢â™¢â™¢â™¢â™¢Ender Pearl Itemâ™¢â™¢â™¢â™¢â™¢

#Pearl name -> Name of the ender pearl (Please use & for color codes).
Pearl-Name: '&2Ender &aPearl'

#Pearl lore -> Any lore lines you would like on the ender pearl (Please use & for color codes).
Pearl-Lore:
  - '&5This is a special ender pearl'
  - '&dYou can ride this like a horse'
  - '&bSimply throw it.'

#See messages.yml for all configurable plugin messages
#â™ If you have any questions please join my discord, open a support ticket and @Mike3132
#â™ https://discord.gg/EHm6Ra3K
#â™ Thanks for downloading and have a wonderful day

#â™›â™›â™›â™›â™› END OF CONFIG â™›â™›â™›â™›â™›
#This is the default file.
